// <auto-generated />
using System;
using DesafioTaskrow.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioTaskrow.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250216180422_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesafioTaskrow.Domain.Models.GrupoSolicitante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GrupoSolicitantePaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoSolicitantePaiId");

                    b.HasIndex("Id");

                    b.ToTable("GruposSolicitantes", (string)null);
                });

            modelBuilder.Entity("DesafioTaskrow.Domain.Models.GrupoSolicitante", b =>
                {
                    b.HasOne("DesafioTaskrow.Domain.Models.GrupoSolicitante", "GruposSolicitantePai")
                        .WithMany("GrupoSolicitanteFilhos")
                        .HasForeignKey("GrupoSolicitantePaiId");

                    b.Navigation("GruposSolicitantePai");
                });

            modelBuilder.Entity("DesafioTaskrow.Domain.Models.GrupoSolicitante", b =>
                {
                    b.Navigation("GrupoSolicitanteFilhos");
                });
#pragma warning restore 612, 618
        }
    }
}
